name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/.cache/coursier/v1
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sc') }}

    - name: Set up java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 14
        java-package: jre

    - name: Build
      run: ./mill _.test